
server.port=9006

spring.application.name=gateway-zuul-demo

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/,http://localhost:8762/eureka/

eureka.instance.prefer-ip-address=true

